name: ColoredNames
main: me.realized.colorednames.Core
version: 1.4.2
author: Realized
description: A fun and cosmetic add-on to Essentials nickname system by Realized.
depend: [Essentials]

commands:
   color:
      description: Change the color of your name!